# Generated by Django 3.0.5 on 2020-06-07 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 15, 56, 43, 367631)),
        ),
    ]
