# Generated by Django 3.0.5 on 2020-06-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addtodo', '0005_auto_20200608_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='datetime',
        ),
    ]
