# Generated by Django 3.0.5 on 2020-06-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addtodo', '0006_remove_todo_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo',
            field=models.CharField(max_length=50),
        ),
    ]
